videojs/videojs-contrib-eme

test/index.html, test/karma/common.js
We aren't running the automated tests in IE and the location they were being included in was causing other browsers to fail. Remove them until we can find a way to include them that doesn't break cross-platform test running.
=> Remove IE-specific sinon hacks that broke tests

src/eme.js, src/plugin.js, test/eme.test.js, test/plugin.test.js
Still trying to get a test asset where the license expires (preferably configurable), but wanted to put this up for review.
=> Close sessions on key expiration and log internal-error key statuses

README.md, src/eme.js, src/fairplay.js, src/ms-prefixed.js, src/plugin.js, test/eme.test.js, test/fairplay.test.js, test/ms-prefixed.test.js
I'm still working through this, this PR is more to clarify on whether the path is the best way to move.
My primary question here is who should trigger the event, currently it is the `player`, but it could be `player.eme` as well.  Input here would be appreciated.
=> Emit event when a license request is attempted

README.md, src/eme.js, src/fairplay.js, src/ms-prefixed.js, src/plugin.js, test/eme.test.js, test/fairplay.test.js, test/ms-prefixed.test.js
Some DRM configurations will block or downscale output when trying to play. With this change, such restrictions can be handled on-the-fly by the player and take appropriate action.
I was debating triggering only events for `output-restricted` and `output-downscaled` statuses, but I think it makes more sense to just keep it generic. That way any future extensions won't need code additions.
Also added a missing TOC entry.
=> Trigger key status changes on player tech

README.md, src/plugin.js, test/plugin.test.js
This is to start a discussion/review around a new API to set up EME directly. This will allow an end user to set up EME on the video element before data is loaded.
=> feat: added API to set media keys directly

README.md, src/eme.js, src/fairplay.js, src/ms-prefixed.js, src/plugin.js, test/eme.test.js, test/fairplay.test.js, test/ms-prefixed.test.js, test/plugin.test.js
Errors in EME will now fire `player.error()`. For spec-compliant EME and Safari, it's promises all the way down.
Also cleaned up the `handleEncryptedEvent` stuff; it was calling `requestMediaKeySystemAccess` twice for every `encrypted`.
Added a bunch of tests to test the various error conditions and make sure they spit out the correct error message strings.
A few things to note:
1. I am using `player.tech_` as an error event bus for IE11 since it doesn't have promises. Those events are then caught and the error handler is called.
2. The tests will fail on IE11, because promises. I may just do a batch exclude of those tests when running on IE11. (this is the same on master)
3. I do not shim `video.msSetMediaKeys` when available since it is apparently read-only and thus can't be assigned to …
=> Promisify all the things and error on player

README.md, src/playready.js, test/ms-prefixed.test.js
The previous code (and tests) had faulty assumptions about the callback signature of a `videojs.xhr()` call. The second argument is _not_ the `responseBody` but the `response` object.
=> fix: Use correct callback function signature for PlayReady license request callbacks.

src/eme.js
PR #81 fixed the callback signature for ms-prefixed, which was
incorrect. However, eme was being used correctly, and so the PR broke
eme support on Edge.
=> fix: use new method signature for requestPlayreadyLicense from #81

README.md, src/eme.js, src/fairplay.js, src/playready.js, src/plugin.js, test/eme.test.js, test/plugin.test.js
Currently the default `getLicense()` functions are permissive in that they won't pass an error to the callback if the request returns something in the 4/500 range. The reason being that in some cases, a license server might return a valid license even if the server sends a code in that range.
We decided it makes sense to change the default behavior to callback with an error for such status codes. If a developer wants to use the old behavior, they can override the default `getLicense()` function by passing their own with `keySystems`.
For status codes >= 400 && <= 599, an empty object is passed as the error (`callback({})`) and `emeError()` has been modified to call `player.error({code: 5, message: null})` in that case, which will use the default `MEDIA_ERR_ENCRYPTED` message ("The media …
=> feat: getLicense should pass an error to callback if XHR returns 400/500

src/eme.js, test/eme.test.js
Instead of always using new options, persist options passed when adding session data to the pendingSessionData array to allow for different options per session created.
This fixes cases where two encrypted pieces of media are in the same manifest, and a user set up the sessions in advance using `initializeMediaKeys`. Previously, the newest options would be used for all sessions. This provides the relevant options.
Because this case occurs when the same manifest has content with different keys, finding a source for testing is a bit of a challenge. I was able to combine two clear key encrypted sources into one manifest using https://github.com/gesinger/encrypted-video-creator, and can share the instructions/content, but the general steps are:
1) Run the script using default options on a …
=> Save session-specific options in pending session data when waiting on media keys

src/eme.js, test/eme.test.js
As per https://www.w3.org/TR/encrypted-media/#dom-mediakeymessagetype there are messageTypes that do not re-request the license.
=> fix: only getLicense on license-request or license-renewal

src/eme.js, test/eme.test.js
Re request the key when the session is expired. This fixes multiple potential issues:
1. The tab was throttled in the background or completely paused, causing the key to never be re-requested.
2. The key request timing was a little off in the server that is being used, causing the session to expire.
3. The request for the key to renew generally takes too long and expires before we renew it.
I don't think we should have any problems doing this because if the user no longer has access to the key or we fail to get the key after expiration then we will still fail to create a new session. If they do still have access though we will get a new session and continue playback as expected.
=> fix: try to re-request key if the session expired

src/eme.js, src/fairplay.js, src/http-handler.js, src/playready.js, src/plugin.js, test/eme.test.js
This adds a new `cause` property to the error object returned by `player.error()` when a license request fails with a 4xx or 5xx status code. It's a string representation, so, if it's JSON a consumer would need to call JSON.parse manually as we can't know whether it's JSON or not.
One way of using it is by listening to the error event and then re-setting the message to be the `cause`
```js
// notice the .one here, otherwise we'd get caught in an infinite loop
player.one('error', () => {
var e = player.error();
player.error(null);
player.error({code: 5, message: e.cause})
});
```
=> feat: on license request errors, return response body as cause

README.md, src/eme.js, src/fairplay.js, src/utils.js
This is to help get around the change in data type of initData between
the legacy API and the standards API.
In the legacy API, the initData was a Uint8Array but needed to be
converted to a Uint16Array to be able to toString it.
In the standards API, initData is an ArrayBuffer but can be converted to
a Uint8Array to be able to toString it.
We now do this string conversion for you so that you can just use the
contentId and not need to figure out whether legacy or standard API is
used.
BREAKING CHANGE: getContentId will now receive a string representation
of the initData
=> fix: convert initData to a string

package-lock.json, package.json, scripts/karma.conf.js, test/fairplay.test.js, test/ms-prefixed.test.js, test/plugin.test.js
This updates the default [browserslist](https://github.com/videojs/babel-config/blob/main/es.js#L6-L19) used by babel. It drops support for some older browsers including IE 11. This also removes the `browserslist` in `package.json` so we use the default list from `@videojs/babel-config` (linked above).
The plan is to merge this into `main` and do a major version release.
**NOTE:** Merge with `BREAKING CHANGE` header
=> chore: Update generate-rollup-config to drop older browser support

package.json, src/plugin.js, src/utils.js
This library was using `videojs.mergeOptions` which will be deprecated in 8.0. This adds code to normalize between Video.js 6.x/7.x (using `videojs.mergeOptions`) and 8.x (using `videojs.obj.merge`).
Also, this removes the fallback on `videojs.plugin()` because that was replaced in either 5.x or 6.x with `videojs.registerPlugin()`. Either way, it wasn't needed.
=> refactor: add support for future Video.js 8.x

src/eme.js, src/plugin.js, test/eme.test.js, test/plugin.test.js
This fixes a bug where a `keySession` could continue to receive events and trigger license requests even after a player is disposed.
Call `keySession.close()` on `'dipose'`. 
Relevant spec: https://www.w3.org/TR/encrypted-media/#x6.-mediakeysession-interface
> A [MediaKeySession](https://www.w3.org/TR/encrypted-media/#dom-mediakeysession) object shall not be destroyed and shall continue to receive events if it is not [closed](https://www.w3.org/TR/encrypted-media/#media-key-session-closed) and the [MediaKeys](https://www.w3.org/TR/encrypted-media/#dom-mediakeys) object that created it remains accessible. Otherwise, a [MediaKeySession](https://www.w3.org/TR/encrypted-media/#dom-mediakeysession) object that is no longer accessible shall not receive further events and may be destroyed. …
=> fix: Close keySession when player is disposed

src/plugin.js
When [cherry-picking commits](https://github.com/videojs/videojs-contrib-eme/pull/183) into the `3.x` branch, a mistake was made while resolving merge conflicts- the `player` was not passed to the `handleEncryptedEvent()` function. This addresses that.
=> fix: missing player argument

.github/workflows/ci.yml
* Update deprecated set-output command. This will stop working in June 2023. See [this post](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/).
* Update actions to use Node 16 rather than Node 12. Github are currently migrating away from Node 12. See [this post](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/).
GabrielBB/xvfb-action is no longer maintained and there is no Node 16 version. Therefore it was replaced with coactions/setup-xvfb.
=> chore: Update CI workflow

src/playready.js, test/playready-message.js, test/playready.test.js
There was an issue on certain platforms, in this case Tizen, where the playready message received from the CDM is already unwrapped. In this case all we need to do is add generic SOAP headers and send the message data straight through to the license request.
=> fix: playready message passthrough

src/playready.js, test/playready-message.js, test/playready.test.js
See: https://github.com/videojs/videojs-contrib-eme/pull/201
same fix for the 3.x branch.
=> fix: playready message passthrough (#201)

scripts/karma.conf.js
We need to disable the karma launcher from running firefox headless as the karma launcher is still broken on updated macs. See: https://github.com/karma-runner/karma-firefox-launcher/issues/328
=> fix: disable firefox headless in karma

README.md, src/fairplay.js, src/plugin.js, test/fairplay.test.js
Due to the way legacy fairplay `com.apple.fps.1_0` was initialized in the plugin, it was broken in v5. This is because Safari has MediaKeys as well as WebkitMediaKeys capabilities, so users attempting to play legacy fairplay content in modern Safari would fall into the `if (window.MediaKeys)` logic.
To avoid this, we check the playerOptions for the legacy keysystem `com.apple.fps.1_0`, if it exists we need to **not** initialize the in spec EME listeners and instead fall to the `else if (window.WebkitMediaKeys)` legacy fairplay initialization.
Additionally, due to the way some players may initialize the options object the legacy fairplay initialization code was added to the API to allow for a player to initialize after the keysystem has been identified.
=> fix: legacy fairplay

package-lock.json, src/plugin.js
I noticed an error as we tried to update to v5.1.0. We were unable to get media keys because the player options had changed between being set at the start of `onPlayerReady` and when they were used in handling the `encrypted` event.
=> Get latest player options when handling encrypted and msneedkey events

src/plugin.js, test/plugin.test.js
Fixes an issue where the player options might not be set by the time the 'encrypted' event listener is attached, which can erroneously follow the `MediaKeys` flow instead of `WebkitMediaKeys` when legacy fairplay is keysystem. Also adds some debug logging to better track this behavior.
...and no, surprisingly the original typo was _not_ the actual problem. 😄
=> fix: getOptions after encrypted event

package-lock.json, package.json, src/eme.js, src/fairplay.js, src/ms-prefixed.js, src/plugin.js, test/eme.test.js, test/fairplay.test.js, test/ms-prefixed.test.js, test/plugin.test.js
This adds new error constants from video.js for a more cohesive errors interface, this also adds some new events for granular insight into the EME workflow.
=> feat: eme error interface

README.md, src/eme.js, src/fairplay.js, src/ms-prefixed.js, src/plugin.js, src/utils.js, test/eme.test.js, test/fairplay.test.js, test/ms-prefixed.test.js, test/utils.test.js
Adding event payloads to most new events and fix tests. Also emit a new event `'keystatuseschanged'`, when the event of the same name is emitted from the `keySession` object, which will pass the entire keyStatusMap as a payload.
=> feat: event payloads

package-lock.json, package.json, src/eme.js, src/fairplay.js, src/ms-prefixed.js, test/eme.test.js, test/fairplay.test.js, test/ms-prefixed.test.js, test/utils.js
fix an issue where the eventBus reference is destroyed before a `keystatuseschange` event is fired after a `despose()` call on the player.
=> fix: eventBus error after dispose

src/plugin.js
Fix legacy eme cleanup issues.
if we call manually cleanup, we set the videoElement reference to null, so when dispose is triggered (auto-cleanup), the reference will be null.
=> fix: fix cleanup issues

src/plugin.js
In cases where a fairplay request fails, the following error was occurring: `TypeError: emeError is not a function. (In 'emeError(err, metadata)', 'emeError' is undefined)`. We simply weren't passing in `emeError` to `handleWebKitNeedKeyEvent()` as was expected.
=> fix: type error with legacy fairplay

src/plugin.js
Add an additional method for manual setup of eme listeners (eg: to cover cases when player.tech.el is changed)
=> feat: add manual setup eme listeners

src/plugin.js
If we attempt to play content with both legacy Fairplay and Widevine DRM configured in Chrome, something like this:
```
{
"com.apple.fps.1_0": {
......
},
"com.widevine.alpha": {
"url": "xxxxxxx.xxxxx.xxxx",
}
},
```
is passed to handleEncryptedEvent, where [this check](https://github.com/videojs/videojs-contrib-eme/blob/8ff427619b00dee2a93aa4dd5472d6814f34b70d/src/plugin.js#L62-L65) detects the presence of the legacy Fairplay configuration, exits out and, as we're in Chrome, playback can't start as Fairplay isn't supported. 
This change adds a simple additional check for `WebKitMediaKeys` for confirmation that the platform supports legacy Fairplay before exiting out of `handleEncryptedEvent`.
=> fix: check for legacy Fairplay support when switching out of handleEncryptedEvent
